### ISSUE TITLE
Input state from camera or map with GPS ?

### ISSUE THREAD

**Issue by jrabary** [urosolia/RacingLMPC#2]
Hi Ugo,

Thank for sharing this code. It really helps to understand the paper. I saw your video that demonstrates the use of this algorithm with a BARC car. I'm wondering wethere you're using the camera as input state to control the car or do you have the map of the track as with the simulator here. If the demo uses a map, how the car is get localized during the race ?

**Comment by urosolia** [comment]
Hi,

Sorry for the late reply. We use an indoor GPS system based on ultrasounds
