### ISSUE TITLE
Typo in comment?

### ISSUE THREAD

**Issue by nkapania** [urosolia/RacingLMPC#3]
In PathfollowingLTIMPC.py -> should be as below:

    # Build matrices for optimization (Convention from http://www.mpc.berkeley.edu/mpc-course-material, Optimal Control Handout, page 4-43, construction of a QP without sub)
    # We are going to build our optimization vector z \in \mathbb{R}^((N+1) \dot n + N \dot d), note that this vector
    # stacks the predicted trajectory x_{k|t} \forall k = t, \ldots, t+N+1 over the horizon and
    # the predicted input u_{k|t} \forall k = t, \ldots, t+N over the horizon

**Comment by urosolia** [comment]
updated
